import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Button, Form, Input } from 'antd';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Online Shop</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
       
      </main>
    </div>
  )
}
